name: federated_cl
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pytorch=1.9.0
  - torchvision=0.10.0
  - torchaudio=0.9.0
  - cudatoolkit=11.1
  - numpy
  - matplotlib
  - networkx
  - pydot
  - tqdm
  - pandas=1.3.5
  - notebook
  - ipywidgets
  - pip
  - pip:
    - gdown